services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: node_app
    environment:
      - NODE_ENV=development
      - MONGO_URI=ur mongo uri
      - JWT_SECRET=your_secret
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app/backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=passwotrd
      - MONGO_INITDB_DATABASE=mydatabase
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
